### ISSUE TITLE
Which clamAV version does pg_snakeoil need?

### ISSUE THREAD

**Issue by harukat** [credativ/pg_snakeoil#1]
Which clamAV version does pg_snakeoil need?
I couldn't build pg_snakeoil with PG10.6 and clamav 0.101.1 on CentOS7.5
and got the following error. It seems to me that older version clamAV is needed.

````
pg_snakeoil.c: In function 'scan_data':
pg_snakeoil.c:163:93: error: 'CL_SCAN_STDOPT' undeclared (first use in this function)
  result.return_code = cl_scanmap_callback(map, &result.virus_name, &result.scanned, engine, CL_SCAN_STDOPT, NULL);

pg_snakeoil.c:163:2: error: too few arguments to function 'cl_scanmap_callback'
  result.return_code = cl_scanmap_callback(map, &result.virus_name, &result.scanned, engine, CL_SCAN_STDOPT, NULL);
````

Please show its tested version.

**Comment by anse1** [comment]
there seems to be an incompatible API change in 0.101 we were not aware
of yet - thanks for reporting.  Version 0.100.2 is the one we tested
with.

**Comment by anse1** [comment]
I pushed a superficially tested patch to make pg_snakeoil work with both
the old and new API.  Can you confirm it works for you?

**Comment by df7cb** [comment]
(See c7360f50fc735c.)

**Comment by harukat** [comment]
Thanks for your quick great work.
It works well in the above environment.
